IGAPP-399: Format dates in right locales
digitalfabrik/integreat-app pull request #2306
Opened 2023-08-14 09:16 UTC by steffenkleinle

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Fixes #1384.

2023-08-14 10:59 UTC, steffenkleinle commented
> I did get an error in iOS though: Error: Invalid DateTime: unparsable: the input "undefined" can't be parsed as ISO 8601

Where exactly did you get that error? Some specific event, page, ...?

2023-08-14 11:00 UTC, LeandraH commented
Sorry, whenever opening a new city

2023-08-14 13:03 UTC, steffenkleinle commented
> Sorry, whenever opening a new city

Not a new issue introduced in my PR, created a new issue: #2314

2023-08-22 11:44 UTC, sarahsporck requested changes
Tested in Firefox and on ios simulator.
On native the page timestamp is not yet correct. And sometimes I randomly get an error  [Error: Invalid DateTime: unparsable: the input "undefined" can't be parsed as ISO 8601]. But not sure where this comes from.

2023-08-22 12:01 UTC, steffenkleinle commented on api-client/src/models/__tests__/__snapshots__/DateModel.spec.ts.snap
> +  "fa: ۶ آذر ۱۳۹۶ - ۷ آذر ۱۳۹۶",
I am guessing that the other localizations were the same for moment as well.

2023-08-22 12:03 UTC, steffenkleinle commented on api-client/src/models/DateModel.ts
> +    if (this.startDate.hasSame(this.endDate, 'day')) {
Actually, it should work. From the docs:
> d1.hasSame(d2, 'day');    // both DateTimes have the same calendar day (which implies they also have the same calendar year and month)

https://moment.github.io/luxon/#/math?id=comparing-datetimes

2023-08-24 10:08 UTC, sarahsporck approved these changes
Tested again and now works fine. As always I forgot that lastUpdate is not controlled by the app language.

2023-08-24 10:35 UTC, merged