2117: Export recurring events
digitalfabrik/integreat-app pull request #2561
Opened 2023-11-13 17:04 UTC by LeandraH

### Short description

Recurring events can be exported in native with this.

### Proposed changes

- The calendar choice layover has been redesigned.
- The user can now choose for recurring events if they want to export only the current one or the entire series.
- The package rn-calendar-events has an odd default duration in Android. I removed that in a patch (and opened an [issue](https://github.com/wmcmahan/react-native-calendar-events/issues/445) in the package, and will open one here to remove our patch if the package is updated)
- Radio buttons have been added.

### Side effects

- The package isn't used anywhere else so there should be no changes from that.
- I made the title of the Modal optional because it would create empty space otherwise.

### Resolved issues

Fixes: #2117 

---

2023-11-14 07:22 UTC, ztefanie reviewed
Wouldn't it make more sense to calculate the duration, than patching the library. Also you wrote in a comment "the end date is not not actually necessary", so for how long should a calendar display an event it there is no duration fallback and no enddate? I think calculating the duration would be best. I like the solution of the library to use a fallback of 1h if there is no duration.

2023-11-14 11:15 UTC, LeandraH commented
> Also you wrote in a comment "the end date is not not actually necessary", so for how long should a calendar display an event it there is no duration fallback and no enddate?

We discussed this a while ago and decided to not add an end date if the event doesn't have one because calendar apps let you choose to delete all future events. So if a user gets annoyed by events in their calendar two months after they originally chose to import all future events, they can delete them with two taps.

I'm not married to that idea though, so if more people think we should add an end date, I'll add one as a fallback. Maybe after 20 events?

2023-11-14 11:27 UTC, LeandraH commented
> Wouldn't it make more sense to calculate the duration, than patching the library. [...] I think calculating the duration would be best. I like the solution of the library to use a fallback of 1h if there is no duration.

The duration of an event is already calculated by the calendars using the outer `endDate` (there are two: one in the `eventOptions` which tells us the end of the current event, and one in the `recurrenceOptions` which really tells us when the last `startDate` is, so also calling it `endDate` is a poor choice). There also seems to not be a way of actually passing in the duration to the library that I have found.

2023-11-14 11:28 UTC, LeandraH commented
Oh, I now see the confusion about the two different kinds of `endDate`. I'll try to make the comment clearer.

2023-11-17 14:00 UTC, f1sh1918 commented
Tested on android.
Facing this error when i want to add a recurring appointent:
<img width="274" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/37902063/5d0ab3bd-5f62-47ae-90aa-92acc29aa182">
Seems like the recurring `endDate` is not parsable

2023-11-17 14:02 UTC, f1sh1918 commented on native/src/components/CalendarChoiceModal.tsx
> +  shadow-radius: 1.41px;
even figma is proposing this we don't use such values. Just use 1px steps

2023-11-17 14:05 UTC, f1sh1918 commented on native/src/components/CalendarChoiceModal.tsx
> +  const [selectedCalendar, selectCalendar] = useState(calendars[0]?.id ?? '')
here is a type missing for the state. i suggest to set null as fallback instead of empty string

2023-11-17 14:19 UTC, f1sh1918 commented on native/src/components/ExportEventButton.tsx
> +      // @ts-expect-error Users don't need to set a last date or a number of occurrences in the CMS
i think its cleaner to override the interface that suppress the error

2023-11-17 14:57 UTC, f1sh1918 commented on native/src/components/ExportEventButton.tsx
> +    let eventOptions: CalendarEventWritable = {
i don't like this `let` and redeclaring tbh.
I personally think its nicer to use a function
```js
// declare function for getting recurrence rule or undefined
const getRecurrenceRule = (variables....): RecurrenceRule | undefined => {
if(exportAll.....)
}
// defining the options once
 const eventOptions : CalendarEventWritable = {
      startDate,
      endDate,
      allDay,
      calendarId,
      location: event.location?.fullAddress,
      description: event.excerpt, // Android
      notes: event.excerpt, // iOS
      recurrenceRule: getRecurrenceRule(vars...)
    }
```

2023-11-20 08:48 UTC, ztefanie commented
> Tested on android. Facing this error when i want to add a recurring appointent: Seems like the recurring `endDate` is not parsable

I get the same error on a Android real device

2023-11-28 11:11 UTC, LeandraH commented
> > Tested on android. Facing this error when i want to add a recurring appointent: Seems like the recurring `endDate` is not parsable
> 
> I get the same error on a Android real device

Oooof, thank you, good catch! Should be fixed now

2023-11-28 11:49 UTC, f1sh1918 commented
> > > Tested on android. Facing this error when i want to add a recurring appointent: Seems like the recurring `endDate` is not parsable
> > 
> > 
> > I get the same error on a Android real device
> 
> Oooof, thank you, good catch! Should be fixed now

i don't see new commits @LeandraH

2023-11-28 11:55 UTC, LeandraH commented
Weird, I just pushed again, try now?

2023-11-30 11:15 UTC, ztefanie commented
Tried again on Android real device, the App is crashing without any error message.
Steps to reproduce
- Checkout Testumgebung
- select Events -> "öffentlichen Plenum"
- click "add to calender"
- i select "My calender" and "this and all future events"
- App closes itself, no event is added to my calender
 
When choosing "only this event" it is working as expected.

2023-12-04 14:21 UTC, f1sh1918 approved these changes
Tested on android (emulator & real device) & ios. works fine now

2023-12-05 15:55 UTC, LeandraH commented on native/src/components/ExportEventButton.tsx
> +    frequency: Frequency[recurrence.options.freq].toLowerCase() as RecurrenceFrequency,
I extracted the frequency into a function and wrote a test for it but I don't think we need to put that into a helper file, it's really quite the one-trick pony.

2023-12-05 17:03 UTC, LeandraH commented
@ztefanie I managed to get one version of the app crashing and fixed that. Can you check again?

2023-12-06 11:08 UTC, steffenkleinle commented on native/src/components/ExportEventButton.tsx
> +              occurrence: event.date.recurrenceRule.options.count ?? 0,
```suggestion
              // This gets overridden by `endDate and can't be set in the CMS anyway 
              occurrence: 0,
```

2023-12-06 15:28 UTC, LeandraH commented
> One thing we might discuss and definitely doesn't have to be done here: I am not that sure if it's a good idea to restrict exporting the same event only once. Imo there is no reason why we should prevent users from exporting events to two or more different calendars. Since this also reduces complexity a bit, I would be in favor to let users export as many times as they want.

That's a good point, we never talked about it, it just seemed natural to me. But we already give the user the feedback that the export worked via the snackbar, so I think I'll leave the button enabled.

2023-12-06 15:29 UTC, LeandraH commented on native/src/components/ExportEventButton.tsx
> +                DateTime.now().plus({ years: 3 }).toUTC().toString(),
One is a JS Date and one is a Luxon one :(

2023-12-06 15:31 UTC, LeandraH commented on native/src/components/ExportEventButton.tsx
> +              occurrence: event.date.recurrenceRule.options.count ?? 0,
Wow, I totally missed that we can't even set the number of occurrences in the CMS, thanks!

2023-12-12 09:10 UTC, ztefanie commented
> @ztefanie I managed to get one version of the app crashing and fixed that. Can you check again?

I just tested with a fresh install, it is still crashing. These are the logs:

```
12-12 10:06:18.773  1645  4598 D CoreBackPreview: Window{8fbe4f u0 app.integreat.test/tuerantuer.app.integreat.MainActivity}: Setting back callback null
12-12 10:06:18.774 16515 16532 E DatabaseUtils: Writing exception to parcel
12-12 10:06:18.774 16515 16532 E DatabaseUtils: java.lang.IllegalArgumentException: Cannot have both DTEND and DURATION in an event
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at com.android.providers.calendar.CalendarProvider2.q1(CalendarProvider2.java:12)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at com.android.providers.calendar.CalendarProvider2.C0(CalendarProvider2.java:175)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at com.android.providers.calendar.CalendarProvider2.k(CalendarProvider2.java:3)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at com.android.providers.calendar.h.insert(SQLiteContentProvider.java:6)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at com.android.providers.calendar.CalendarProvider2.insert(CalendarProvider2.java:3)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at android.content.ContentProvider.insert(ContentProvider.java:1819)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at android.content.ContentProvider$Transport.insert(ContentProvider.java:348)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:168)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at android.os.Binder.execTransactInternal(Binder.java:1316)
12-12 10:06:18.774 16515 16532 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:1280)
12-12 10:06:18.776 20402 21818 E AndroidRuntime: FATAL EXCEPTION: Thread-49
12-12 10:06:18.776 20402 21818 E AndroidRuntime: Process: app.integreat.test, PID: 20402
12-12 10:06:18.776 20402 21818 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot have both DTEND and DURATION in an event
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:2200)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:2162)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at com.calendarevents.RNCalendarEvents.addEvent(RNCalendarEvents.java:710)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at com.calendarevents.RNCalendarEvents.access$300(RNCalendarEvents.java:44)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at com.calendarevents.RNCalendarEvents$4.run(RNCalendarEvents.java:1327)
12-12 10:06:18.776 20402 21818 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
12-12 10:06:18.781 20402 20402 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@41b40d1[MainActivity]
12-12 10:06:18.785 20402 20472 D OpenGLRenderer: setSurface called with nullptr
12-12 10:06:18.785 20402 20472 D OpenGLRenderer: setSurface() destroyed EGLSurface
12-12 10:06:18.785 20402 20472 D OpenGLRenderer: destroyEglSurface
12-12 10:06:18.786  1645 21819 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-12 10:06:18.786  1645 11287 D Debug   : low && ship && 3rdparty app crash, do not dump
12-12 10:06:18.787  1645 11287 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 com.android.server.am.AppErrors.crashApplicationInner:722 com.android.server.am.AppErrors.crashApplication:598 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:10480 com.android.server.am.ActivityManagerService.handleApplicationCrash:10349 
12-12 10:06:18.787  1645 11287 W ActivityManager: crash : app.integreat.test,10453
12-12 10:06:18.787  1645 11287 W ActivityTaskManager:   Force finishing activity app.integreat.test/tuerantuer.app.integreat.MainActivity
12-12 10:06:18.788 20402 20402 I ViewRootImpl@d4d0c2[MainActivity]: dispatchDetachedFromWindow
1
```

2023-12-12 09:11 UTC, ztefanie requested changes
see comment above

2023-12-12 16:05 UTC, LeandraH commented
I still haven't been able to reproduce it (did learn how to add a Samsung skin to Android Studio, though 💪 ) but found [this crash report](https://github.com/wmcmahan/react-native-calendar-events/issues/159) with your log, thank you very much! Could you test again @ztefanie ?

2023-12-13 08:27 UTC, ztefanie approved these changes
Works as expected

2023-12-13 09:50 UTC, merged