2569: Test CategoriesToolbar.tsx
digitalfabrik/integreat-app pull request #2625
Opened 2024-01-09 10:11 UTC by Njivaniaina2407

### Short description

Create a CategoriesToolbar.spec.tsx file and   write a test that checks whether the correct PDF URL is used in case:
- Category is a root category
- Category is not a root category

### Proposed changes

Creating the CategoriesToolbar.spec.tsx file and writing the test 

### Side effects

### Resolved issues

Fixes: #2569

---

2024-01-11 08:42 UTC, ztefanie requested changes

2024-01-24 15:16 UTC, steffenkleinle approved these changes
Looking good! :tada:

2024-01-29 08:37 UTC, ztefanie approved these changes
Well done :muscle: :rocket:

2024-01-30 08:55 UTC, steffenkleinle commented on web/src/components/__tests__/CategoriesToolbar.spec.tsx
> +import { CategoryModel } from 'api-client'
We renamed/moved the whole api-client, so you have to change this to
```suggestion
import { CategoryModel } from 'shared/api'
```

2024-01-30 12:31 UTC, merged