2966: Migrating to Modern Yarn
digitalfabrik/integreat-app pull request #2968
Opened 2024-10-22 10:55 UTC by bahaaTuffaha

### Short description

Upgraded to `yarn@4.5.1`

### Proposed changes

- yarnrc.yml will have `nodeLinker: node-modules` meaning its not depending on pnp more on that at (https://yarnpkg.com/features/pnp) 
Note we can do hybrid pnp in the future look at https://yarnpkg.com/getting-started/recipes#hybrid-pnp--node_modules-mono-repo

- `nohoist` is deprecated so I removed it and added `nmHoistingLimits: workspaces`

- This yarn version at some places it complains about `--silent` so I removed some of them. Still looking for a way to silent these warnings.

Note: not tested on iOS and focused mainly on integrate native and integrate web app.

### Side effects

Not sure

### Testing

- I used this time: Node 22.9.0 you can install by nvm

- before `yarn install` make sure to run `corepack enable` once to activate Corepack.

- I suggest to delete all node modules files from the repo then do yarn install. 

### Resolved issues

Fixes: #2966 

---

2024-10-22 11:15 UTC, LeandraH commented
Thank you, I probably won't manage to have time today to take a look at it but maybe also check out this old PR that was never merged to see what went wrong there and if this PR fixes the issues: https://github.com/digitalfabrik/integreat-app/pull/2588

2024-10-22 11:25 UTC, bahaaTuffaha commented
> Thank you, I probably won't manage to have time today to take a look at it but maybe also check out this old PR that was never merged to see what went wrong there and if this PR fixes the issues: #2588

I found out it needs to be bit more in the oven.. sorry.. yarn test is not working I'm investigating...I will convert this PR to Draft for now

2024-10-28 18:00 UTC, LeandraH reviewed
Just a few small comments, as discussed on Mattermost, next thing to do is get the commands in the `package.json` files to work in their respective folders.

2024-10-29 14:19 UTC, bahaaTuffaha commented on native/package.json
> +    "ts:check": "yarn ts:check",
https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces

2024-10-29 14:30 UTC, LeandraH commented on native/package.json
> +    "ts:check": "yarn ts:check",
Hmmm, sorry, but I don't understand what sharing scripts between different workspaces has to do with it being a circular dependency. This command would run in the folder it is run in, in this case `/native`, not in the `root`. Is this maybe the wrong link? Or if not, could you elaborate a little on why you think this applies here?

Also, I thought we agreed that we want the commands that are run in a folder to only run in that folder? I guess we could add global commands to each but I'm not sure that's necessary, you can always just do `cd ..` and then run the global command.

2024-10-29 14:35 UTC, bahaaTuffaha commented on package.json
> +    "g:lint": "eslint --cache --cache-location .eslintcache . && yarn workspace web stylelint && yarn workspace native stylelint",
😅 one for the current dir and the other for other workspaces...

2024-10-29 14:46 UTC, LeandraH commented on native/android/app/buildConfigs.gradle
> +    return execCommand("yarn workspace build-configs manage $command $buildConfigName $platform")
Interesting, looks like it has been completely removed, thanks for looking into it!
https://github.com/yarnpkg/berry/issues/3542

2024-10-29 14:50 UTC, LeandraH commented on package.json
> +    "g:lint": "eslint --cache --cache-location .eslintcache . && yarn workspace web stylelint && yarn workspace native stylelint",
Two things:
1. This is at root, so there isn't really any code in this directory to be linted.
2. If I now execute `yarn lint` in the root directory, yarn checks in `package.json` what to do for the command `lint` and sees that it should execute `yarn g:lint`. Which is the command in line 18. So both commands do the same thing with line 17 just being a reference to line 18. I don't think that's necessary.

2024-11-25 10:53 UTC, bahaaTuffaha commented on web/package.json
> +    "htmlparser2": "^9.1.0",
There was an error that has to do with htmlparser2 so I added this dependency

2024-11-25 10:56 UTC, bahaaTuffaha commented on web/package.json
> +    "rrule": "2.8.1",
Ok I didn't find a way to let the dev dependences use the ones at the root folder thats way you will see that I added `jest`, `stylelint`,`typescript` and `prettier`
- I know its duplicated but what else to do? and its a dev-dependency after all.

2024-11-25 10:58 UTC, bahaaTuffaha commented on native/run
> +function parseBashVariables(str) {
I know this sounds bad but this what chat suggested to solve a problem that has to do with a long command in cmd (Error: spawnSync C:\WINDOWS\system32\cmd.exe ENAMETOOLONG
) when I run "start:malte" or "android:malte"

2024-12-04 09:22 UTC, steffenkleinle requested changes
Thanks for your PR. The reason why we were not able yet to upgrade yarn to modern were memory problems in the CI (see https://github.com/yarnpkg/berry/issues/3996 and https://github.com/digitalfabrik/integreat-app/issues/2026). Did you check that this issue is solved? Otherwise this will cost us lots of CI credits if we have to upgrade to bigger images. Therefore, please make sure that it still works in the CI. I sadly doubt that this issue is fixed as https://github.com/yarnpkg/berry/issues/3996 is still open.

Furthermore, please revert all changes that are not necessary, e.g.
- changes to autogenerated fastlane readmes
- adding shared dependencies to web
- removing tools yarn.lock
- updating gradle (should only be done in react-native upgrades)
- and others

Not sure if it is worth to invest the time though as long as the memory problem exists :/

2025-01-22 07:36 UTC, steffenkleinle commented
@bahaaTuffaha what is the status here? Are you still working on this?

2025-01-22 11:50 UTC, steffenkleinle commented
Okay, then I think we should close this issue and PR until this changes.

2025-01-22 13:51 UTC, closed without merging