2918 add tts on web
digitalfabrik/integreat-app pull request #2985
Opened 2024-11-06 12:59 UTC by bahaaTuffaha

### Short description

Adding text-to-speech functionality for web.

### Proposed changes

- `TtsPlayer.tsx` will receive content and title from `useTtsPlayer.ts` hook then it will process content as following:
     - Adding period to any `<p>` or `<li>` tag if there is non at the end.
     - Splitting the content using a library `sentencex` to support most languages.
     - Adding the title to the array.
- `TtsPlayer.tsx` using EasySpeech library for web speech api .. why I used it instead of directly using the native api read here: https://github.com/leaonline/easy-speech/blob/master/FAQ.md#why-does-this-library-exists-if-i-can-use-tts-natively-in-the-browser
- Web Speech API has some limitation on devices like Android I can't pause so I implemented a way to increment `currentSentencesIndex` at each sentence so pausing will be depend on sentence index . Another issue with Firefox about triggering onEnd function at any `.cancel()` method unlike chromium based browsers (added useeffect to check whether it reached the last index or not ... Note : sometimes content gets finished reading before reaching end of the array)

- This is different from tts-native: voices needs to be installed from OS so a modal will show up `TtsHelpModal` to guide users for each platform. Note: by default for windows for example you have what the keyboard layout have of languages also it may need a restart to see the newly installed language.

- Modified Modal.tsx to accept new props: icon and styling just for (backgroundColor, borderRadius)

- Notes:
    - boundaryGuard is created just to prevent handleBoundary from incrementing again incases like handleForward or handleBackward (I'm still not sure about this function as I did it out of frustration 😂)
    - Not Tested on iOS !

### Side effects

- CityContentToolbar.tsx, CategoriesPage.tsx, LocalNewsPage.tsx, TuNewsDetailPage.tsx, RemoteContent.tsx

### Testing

- At integreat : Go to any 3rd level content in categories or news.
- Click on ToolbarItem on the side called readAloud
- The player will show up press play to make it start reading content.

### Resolved issues

Fixes: #2918 

---

2024-12-13 11:17 UTC, ztefanie reviewed
Nice work :rocket: 

Tested this on chrome and firefox.

Firefox voice is really crappy, but chrome is really nice :rocket: Maybe we add hint, that some browsers better support this feature? Maybe @hauf-toni can share some input, how to handle this best from a UI perspective.

Found a few bug:

issue 1:
1) Open this page: http://localhost:9000/augsburg/de/willkommen/willkommen-in-augsburg-2
2) Click "read aloud"
3) Click "play"
4) Click on "Weiter"
Result: The reader starts reading out the beginning of the current sentance, when clicking "weiter" for the first time. When clicking "weiter" a second time, it correctly jumps to the next sentance
Expected result: When clicking "weiter" for the first time, it should directly jump to the next sentance.

issue 2:
When opening this page: http://localhost:9000/augsburg/de/willkommen
the "read aloud" button is displayed, but does nothing when clicked.
Expected: Should either not be displayed or does something when clicked

issue 3: 
Open this page: http://localhost:9000/augsburg/de/behoerden-beratung/behoerden/auslaenderbehoerde
Click "next" to jump to the last sentance
in this line "Weitere Informationen finden Sie unter [hier]" the reader switches to the "start"-mode, but there is still this whole contact blog that is read 


issue 4: 
When clicking pause I see the initial view of the tts-player, with the first word of the page in the heading. I think this is confusing, as clicking play does not continue reading from the beginning. I would expect that the player just changes the pause button to showing a play button.
what i get when i click pause
![pause-is](https://github.com/user-attachments/assets/7e196478-e448-4586-aa75-aaefa8759812)
what i expected
![pause2](https://github.com/user-attachments/assets/2dec1490-5ce0-4d01-a90c-37e3f25e2e79)

issue 5:
on firefox when the tts reaches the end of the text, the player does not reset to start as it is for other browsers.

2024-12-13 12:18 UTC, bahaaTuffaha commented
> issue 1:
> 
> 1. Open this page: http://localhost:9000/augsburg/de/willkommen/willkommen-in-augsburg-2
> 2. Click "read aloud"
> 3. Click "play"
> 4. Click on "Weiter"
>    Result: The reader starts reading out the beginning of the current sentance, when clicking "weiter" for the first time. When clicking "weiter" a second time, it correctly jumps to the next sentance
>    Expected result: When clicking "weiter" for the first time, it should directly jump to the next sentance.
> 
> issue 2: When opening this page: http://localhost:9000/augsburg/de/willkommen the "read aloud" button is displayed, but does nothing when clicked. Expected: Should either not be displayed or does something when clicked
> 
> issue 3: Open this page: http://localhost:9000/augsburg/de/behoerden-beratung/behoerden/auslaenderbehoerde Click "next" to jump to the last sentance in this line "Weitere Informationen finden Sie unter [hier]" the reader switches to the "start"-mode, but there is still this whole contact blog that is read

can you please mention which browser you used for each issue?

2024-12-16 08:17 UTC, ztefanie commented
> 
> Can you please mention which browser you used for each issue?

I mostly used Chrome, sometimes I double checked with Firefox

2025-01-09 11:55 UTC, bahaaTuffaha commented on web/src/components/TtsPlayer.tsx
> +              <StyledBackForthButton label='backward-button' onClick={playPrevious}>
Its used by default in the button:
![image](https://github.com/user-attachments/assets/91516101-5278-45c3-ad1d-4af31802ac74)

2025-01-09 12:03 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +      }).catch(() => null)
At chrome this will throw interrupted errors..

2025-01-09 12:49 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +      } else if (currentSentencesIndex !== 0 && !isAndroid) {
I added a comment:
`// FirefoxAndLinux and isAndroid can't resume`

2025-01-21 18:15 UTC, bahaaTuffaha commented on build-configs/integreat/index.ts
> +    tts: false,
@steffenkleinle what do you think?

2025-01-22 06:49 UTC, steffenkleinle commented on build-configs/integreat/index.ts
> +    tts: false,
Yes, I think so. Until iOS is ready as well I think we only want this on beta :)

2025-01-22 10:55 UTC, bahaaTuffaha commented on build-configs/integreat/index.ts
> +    tts: false,
Ok I will turn this to true 👍️

2025-01-22 11:17 UTC, steffenkleinle commented on build-configs/integreat/index.ts
> +    tts: false,
sorry, badly phrased from my side. This should stay false until ios is ready.

2025-01-29 15:47 UTC, LeandraH reviewed
This looks very good already, thank you! Tested in Firefox on OS X

A couple of small things:

~I would prefer that the overlay doesn't change size based on whether or not the text is being read.~ I hear that will be a separate issue :)

There were a lot of very random CSS numbers, please already apply the multiples-of-four rule of thumb that Toni mentioned when introducing the new style guide.

Also, I'm getting an unfortunate word separation in German, maybe increase the width of the side bar.
<img width="151" alt="image" src="https://github.com/user-attachments/assets/589d26b0-362d-4eaf-9c20-9d2077c14d9f" />

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/TtsPlayer.tsx
> +  border-color: transparent;
I don't think this line does anything

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/TtsPlayer.tsx
> +  ${buttonBaseStyles}
🔧 You could make a styled base button that you then use instead of importing the styles, so something like this:

```javascript
const BaseButton = styled(Button)`
  display: flex;
  justify-content: center;
  align-items: center;
  transition:
    box-shadow 0.2s ease,
    transform 0.1s ease;
  &:active {
    box-shadow: none;
    transform: translateY(2px);
  }
`

const StyledPlayIcon = styled(BaseButton)`
...
```

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/TtsPlayer.tsx
> +              <StyledBackForthButton label='backward-button' onClick={playPrevious}>
Nice! The labels should be translated, though :)

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/__tests__/RemoteContent.spec.tsx
> +// Import MemoryRouter if not included in renderWithTheme
Please delete the comments from the generator ;)

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/__tests__/RemoteContent.spec.tsx
> +      </MemoryRouter>,
Maybe write a short function to not repeat this so often

2025-01-29 15:47 UTC, LeandraH commented on web/src/components/__tests__/TtsContainer.spec.tsx
💭 I don't love this test because it really tests the implementation of the component as opposed to testing roughly how a user would use the component. On the other hand, it's really hard to test third-party components, and then ones playing sounds. Not sure what to do here

2025-01-29 15:47 UTC, LeandraH commented on web/src/contexts/TtsContextProvider.tsx
> +}
```suggestion
}

```

2025-01-29 15:47 UTC, LeandraH commented on web/src/contexts/TtsContextProvider.tsx
> +})
```suggestion
})

```

2025-01-29 15:47 UTC, LeandraH commented on web/src/contexts/TtsContextProvider.tsx
> +}
```suggestion
}

```

2025-01-29 15:47 UTC, LeandraH commented on web/src/hooks/useTtsPlayer.ts
> +  }, [model, languageCode])
💭 Hmmm, I don't like this hack to break up the content, and I see that you didn't do it in the native one. Maybe there is a better solution here?

2025-01-29 18:20 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +        // FirefoxAndLinux and isAndroid can't resume
I think steffi asked for these comments.. sure I will remove them 😐️

2025-01-29 18:24 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +  const enableOnEnd = useRef(true)
`onEnd` is function that will run at the end of a speech .. this ref is for guarding the `onEnd` from running.

2025-01-29 18:26 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +  const playOnFallback = (index?: number) => {
It will play in case of the player didn't play... simple 😎

2025-01-29 18:34 UTC, bahaaTuffaha commented on web/src/hooks/useTtsPlayer.ts
> +  }, [model, languageCode])
hmm at native it stops normal at the end of sentences but at web I noticed lists and paragraphs without full stop will continue reading the next sentence as it one.

Other option is maybe changes from CMS ?

2025-01-30 09:14 UTC, f1sh1918 commented
> This looks very good already, thank you! Tested in Firefox on OS X
> 
> A couple of small things:
> 
> ~I would prefer that the overlay doesn't change size based on whether or not the text is being read.~ I hear that will be a separate issue :)
> 
> There were a lot of very random CSS numbers, please already apply the multiples-of-four rule of thumb that Toni mentioned when introducing the new style guide.
> 
> Also, I'm getting an unfortunate word separation in German, maybe increase the width of the side bar.
> <img width="151" alt="image" src="https://github.com/user-attachments/assets/589d26b0-362d-4eaf-9c20-9d2077c14d9f" />
> 

Maybe can also adjust css styles to only break word

2025-01-30 19:22 UTC, bahaaTuffaha commented on web/src/components/Modal.tsx
> +  border-radius: ${props => (props.$style?.borderRadius != null ? props.$style.borderRadius : 0)}px;
I think I've already tried that

2025-01-30 19:53 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +  const isFirefoxAndLinux = isFirefox && isLinux
It matters... different platform have different behaviors with tts

2025-01-30 20:00 UTC, bahaaTuffaha commented on web/src/components/TtsPlayer.tsx
> +  border-color: transparent;
without it:
![image](https://github.com/user-attachments/assets/03e9f9eb-b903-453b-836c-24548c8f2bca)

2025-02-03 16:47 UTC, LeandraH commented on web/src/components/TtsContainer.tsx
> +  const isFirefoxAndLinux = isFirefox && isLinux
Your code doesn't use `isLinux` anywhere other than in `isFirefoxAndLinux`, and you don't use `isFirefox` anywhere other than `isFirefoxAndLinux`. So you can do `const isFirefoxAndLinux = userAgent.toLowerCase().includes('firefox') && userAgent.toLowerCase().includes('linux')` without affecting the legibility.

2025-02-03 17:42 UTC, LeandraH approved these changes
Very cool, thank you so much! This is such a complicated feature, and you made it through that!

Tested in Firefox

2025-02-03 17:42 UTC, LeandraH commented on web/src/components/CityContentToolbar.tsx
> +        tooltipContent={t('layout:nothingToReadFullMessage')}>
You're already in the layout context in the translation file :)

2025-02-03 17:42 UTC, LeandraH commented on web/src/components/ModalContent.tsx
> +          {!!icon && icon}
```suggestion
          {icon}
```

2025-02-03 17:42 UTC, LeandraH commented on web/src/components/TtsContainer.tsx
> +  const enableOnEnd = useRef(true)
Hmmm, I think a better name would help making it clearer why we need it :)

2025-02-03 17:42 UTC, LeandraH commented on web/src/components/TtsContainer.tsx
> +  const playOnFallback = (index?: number) => {
So, this plays in case there is an error with playing the sound but there shouldn't be, am I understanding this correctly? Then I would rename it to `fallbackPlay`, I think

2025-02-04 11:56 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +  const playOnFallback = (index?: number) => {
This is the fallback ... sometimes the player will stop for no reason so this will check its running while `isPlaying` is true and speechSynthesis.speaking is not .. so it triggers the play again 🙂

2025-02-04 12:03 UTC, LeandraH commented on web/src/components/TtsContainer.tsx
> +  const isFirefoxAndLinux = isFirefox && isLinux
Good thinking, though!

2025-02-11 13:42 UTC, f1sh1918 approved these changes
👍 Nice work.
Voice on macos safari is really crappy but thats not you fault

I have on styling suggestion. Can you please increase the spacing between these two button. On mobile its very close and closing and playing should have a proper distance

<img width="228" alt="image" src="https://github.com/user-attachments/assets/1e32d086-599c-427a-8ad2-bf522760f531" />

2025-02-11 13:42 UTC, f1sh1918 commented on build-configs/common/theme/colors.ts
> +  ttsPlayerWarningBackground: 'rgba(255, 253, 230, 1)',
:wrench: is there any reason for using rgba here?
If not please convert it to hex

2025-02-11 13:42 UTC, f1sh1918 commented on web/src/components/TtsContainer.tsx
> +        volume: 0.6,
we should add a rate here. For me on firefox its super fast and on chrome its okay with default rate.
It doesn't look like the default is for both browsers the same
`rate: 0.8`
worked good for me

2025-02-11 13:42 UTC, f1sh1918 commented on web/src/components/TtsHelpModal.tsx
> +  width: 72%;
can you explain why you use this width? Looks quite random

2025-02-11 16:15 UTC, bahaaTuffaha commented on web/src/components/TtsHelpModal.tsx
> +  width: 72%;
because it's a multiple of 4 number 😅

2025-02-12 13:01 UTC, steffenkleinle commented on web/src/components/TtsHelpModal.tsx
> +    <Modal
:x: I am not able to close the modal, neither by pressing the x button nor the overlay around the modal.

2025-02-12 13:02 UTC, steffenkleinle commented on web/src/components/CityContentToolbar.tsx
> +    }, COPY_TIMEOUT)
:question: Why do we need a timeout to show the tooltip? I think the item should just be disabled if there is nothing to read with a normal tooltip explaining the reason. Compare to the tooltips for language change/location change for reference.

2025-02-12 13:05 UTC, steffenkleinle commented on web/src/components/TtsPlayer.tsx
> +            style={{ flexDirection: theme.contentDirection === 'rtl' ? 'row-reverse' : 'row' }}>
:wrench: Please avoid inline styling, pass the language instead and apply the style in the styled component.

2025-02-12 13:07 UTC, steffenkleinle commented on web/src/components/TtsPlayer.tsx
> +const BackForthIcon = styled(Icon)<{ $flip: boolean }>`
:wrench: We have this functionality implemented. Please use the prop `reverse` instead.

2025-02-12 13:08 UTC, steffenkleinle commented on web/src/components/TtsPlayer.tsx
> +              togglePlayPause()
:wrench: Is it necessary to pause here? If I understood correctly, the help modal is only shown if it is not possible to read anything anyway as no voice is installed?

2025-02-12 13:09 UTC, steffenkleinle commented on web/src/components/TtsPlayer.tsx
> +            }}
:question: From a user flow I find it very confusing that this modal is only shown once I press play on the tts player. I would expect it to be directly shown once clicking on `read aloud` :thinking:

2025-02-12 13:11 UTC, steffenkleinle commented on web/src/components/TtsPlayer.tsx
> +  if (isVisible) {
:wrench: Please flip the condition to avoid the indentation which makes it less readable.
```suggestion
  if (!isVisible) {
    return null
  }
  
  return (
  ...
```

2025-02-12 18:40 UTC, bahaaTuffaha commented on web/jest.setup.ts
> +jest.mock('sentencex', () => jest.fn())
I remember jest was complaining so I added these 2 lines.

2025-02-12 18:49 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +import EasySpeech from 'easy-speech'
This will leave everything in one place... but sure I will do it anyway 😐

2025-02-12 19:04 UTC, bahaaTuffaha commented on web/src/components/TtsContainer.tsx
> +import EasySpeech from 'easy-speech'
I just remembered : because the useTtsPlayer uses `useLocation` hook and if I did placed <TtsContainer> in app like native it will show errors due to its location above (parent) the Router.

2025-02-12 19:33 UTC, bahaaTuffaha commented on web/src/components/TtsHelpModal.tsx
> +  width: 72%;
what is more annoying is the font-size is smaller now because it was 14 /4 = 3.5 so I had to move it to 12.
I'm thinking of changing it to 16px..

2025-02-12 19:41 UTC, bahaaTuffaha commented on web/src/components/CityContentToolbar.tsx
> +    }, COPY_TIMEOUT)
This timeout to hide the tooltip not to show it 😅

2025-02-12 19:52 UTC, bahaaTuffaha commented on web/src/components/Modal.tsx
> +  style?: ModalContentStyling
Oh I did changes and forgot to remove these... I was passing value from css to styled-components or the opposite.
Nice catch!

2025-02-12 20:35 UTC, bahaaTuffaha commented on web/src/components/StyledSmallViewTip.tsx
> +  white-space: nowrap;
![image](https://github.com/user-attachments/assets/431d8215-b697-414b-a97b-27abf02db182)

2025-02-12 20:38 UTC, bahaaTuffaha commented on web/src/components/TtsHelpModal.tsx
> +    <Modal
what browser did you use?

2025-02-13 08:07 UTC, steffenkleinle commented on web/src/components/TtsContainer.tsx
> +import EasySpeech from 'easy-speech'
Any reason not to move it inside of the router?

2025-02-13 17:36 UTC, bahaaTuffaha commented on web/src/components/TtsPlayer.tsx
> +              togglePlayPause()
Yes sometimes it says undefined

2025-02-13 17:45 UTC, bahaaTuffaha commented on web/src/components/TtsPlayer.tsx
> +  if (isVisible) {
I will remove it anyway I move the visibility check at ttsContainer

2025-02-15 08:35 UTC, steffenkleinle commented on web/src/components/StyledSmallViewTip.tsx
> +  white-space: nowrap;
Thanks for explaining, looks good :+1:

2025-02-15 08:35 UTC, steffenkleinle commented on web/src/components/TtsHelpModal.tsx
> +    <Modal
firefox

2025-02-17 11:29 UTC, bahaaTuffaha commented on web/src/components/TtsHelpModal.tsx
> +    <Modal
I have seen that with brave because it doesn't have voices/api so easySpeech will throw an error ... not sure if we can catch it 🫠

2025-02-17 11:36 UTC, steffenkleinle commented on web/src/components/TtsHelpModal.tsx
> +    <Modal
I don't think that is related. This is just that the modal cant be closed.

2025-02-20 12:05 UTC, LeandraH commented on web/src/components/TtsHelpModal.tsx
> +  width: 72%;
The multiples of four is mostly for the size of elements and empty spaces between them, a font-size of 14px is totally fine.

2025-02-21 16:04 UTC, f1sh1918 commented
@bahaaTuffaha i just found one issue.
1. Go to a third level page and open the  player
2. Move to a first level page
3. The Play button should be disabled if there is nothing to read. At least its the case for native implementation

<img width="445" alt="image" src="https://github.com/user-attachments/assets/27d73b2a-1897-499a-bbeb-21da9901f62f" />

2025-02-26 11:36 UTC, steffenkleinle commented on native/src/hooks/useTtsPlayer.ts
> +        const sentences: string[] = segmentation(languageCode, addingPeriodsToDom(model.content))
:question: Why do we need periods here now?

2025-02-26 11:51 UTC, bahaaTuffaha commented on native/src/components/TtsContainer.tsx
>    }, [])
This is just for codeSence (the plugin suggested this)

2025-02-26 11:59 UTC, steffenkleinle commented on native/src/components/TtsContainer.tsx
>    }, [])
Hmm, if CodeScene suggests this I don't think its a good suggestion :D  It only makes the code more complicated, not less. I will revert this.

2025-02-26 11:59 UTC, steffenkleinle commented on web/src/hooks/useTtsPlayer.ts
> +    }
Okay, I will check.

2025-02-26 12:01 UTC, bahaaTuffaha commented on native/src/hooks/useTtsPlayer.ts
> +        const sentences: string[] = segmentation(languageCode, addingPeriodsToDom(model.content))
hmm .. not actually needed for native but keeping the web and native consistent.
In general I think tts for native works differently and as I remember it didn't need a period to figure out when to stop unlike web.

2025-02-26 12:03 UTC, bahaaTuffaha commented on native/src/components/TtsContainer.tsx
>    }, [])
The health increased from this BTW 😂😂

2025-02-26 12:41 UTC, steffenkleinle commented on native/src/components/TtsContainer.tsx
>    }, [])
it did get better or worse?

2025-02-26 16:15 UTC, bahaaTuffaha commented on native/src/components/TtsContainer.tsx
>    }, [])
better from what the plugin says...

2025-03-12 09:53 UTC, steffenkleinle commented on native/src/hooks/useTtsPlayer.ts
> +        const sentences: string[] = segmentation(languageCode, addingPeriodsToDom(model.content))
Could reproduce on firefox linux.

2025-03-14 19:12 UTC, bahaaTuffaha commented on native/src/hooks/useTtsPlayer.ts
> +        const sentences: string[] = segmentation(languageCode, addingPeriodsToDom(model.content))
> Actually, I can't. Everything works as expected for me and the tts correctly jumps to the next sentence after each utterance/sentence, even without adding extra periods. Could you please test this and add concrete info on how to reproduce this?

Comment out the following lines at `ttsDomManipulation.ts`:
  appendPeriod(paragraphs)
  appendPeriod(listItems)

At firefox (anything doesn't have a full stop at the end will continue reading like lists): 
http://localhost:9000/muenchen/en/everyday-life/information-on-insurance-contracts-shopping-invoices-reminders-finances/bank-account

2025-03-17 09:03 UTC, steffenkleinle commented on web/src/hooks/useTtsPlayer.ts
> +    }
Couldn't find any problems with removing so removed in #3150.

2025-03-26 06:47 UTC, steffenkleinle approved these changes

2025-03-31 11:33 UTC, f1sh1918 requested changes
Unfortunately safari breaks with this error if i click pause

<img width="603" alt="image" src="https://github.com/user-attachments/assets/542f6396-6c33-479f-9ccf-1f098b21ce5e" />

2025-03-31 11:57 UTC, f1sh1918 reviewed
@steffenkleinle i fixed some issues for safari
@LeandraH could you please test the tts player especially for safari. The voice should now sound better and start/stop should work

I tested tts on chrome, safari and firefox

2025-03-31 12:24 UTC, f1sh1918 approved these changes
Tested on chrome, firefox and safari

2025-03-31 13:09 UTC, steffenkleinle commented
> Tested on chrome, firefox and safari
> 
> Update: Okay the big issue is that not all voices work good on all browsers. For a particular language are different voices available so i can not define one standard voices which leads to the question how to solve that. We would have to check for every language all the voices for every browser

Thanks for the testing and fixing! I think we should then delegate this to the user, i.e. it is then the users responsibility to select a voice that works well in their language + browser. I don't think we can/should test all combinations of voices + languages + browsers...

2025-04-01 11:11 UTC, steffenkleinle commented
> Tested on chrome, firefox and safari
> 
> Update: Okay the big issue is that not all voices work good on all browsers. For a particular language are different voices available so i can not define one standard voices which leads to the question how to solve that. We would have to check for every language all the voices for every browser

Created https://github.com/digitalfabrik/integreat-app/issues/3174 to handle the voices issue on safari.

2025-04-01 11:30 UTC, merged