IGAPP-974: Unify viewport constants
digitalfabrik/integreat-app pull request #645
Opened 2022-04-04 09:29 UTC by Schedulaar

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2022-04-04 09:52 UTC, klinzo reviewed
:tada: Layout is currently completely broken, see suggestion below. With that applied everything  should work fine.

Could you perhaps add a release note? Like this: https://github.com/digitalfabrik/integreat-app/blob/main/release-notes/unreleased/IGAPP-927-use-image-alignment.yml

2022-04-04 09:52 UTC, klinzo commented on web/src/constants/dimensions.ts
> +  smallViewport: '(max-width: 768px',
```suggestion
  smallViewport: '(max-width: 768px)',
```

2022-04-04 09:52 UTC, klinzo requested changes
see above

2022-04-04 10:42 UTC, klinzo approved these changes

2022-04-05 10:41 UTC, f1sh1918 approved these changes

2022-04-05 11:29 UTC, merged