IGAPP-1005: Removed double separation line in location list view mobile
digitalfabrik/integreat-app pull request #689
Opened 2022-06-07 15:56 UTC by f1sh1918

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2022-06-11 10:26 UTC, Cmd190 commented
Tested on chrome, edge and firefox on Windows. The double seperation line is still shown on "middle" window size in firefox. See screenshot below.
 
![image](https://user-images.githubusercontent.com/75899673/173183963-0389f5bd-cd69-487d-9f4c-32dbf28e58b3.png)
(left: chrome; right: firefox)

2022-06-13 09:20 UTC, SteffiStuffel approved these changes
Tested on chrome, double line is not shown. :tada:

2022-06-23 08:46 UTC, steffenkleinle requested changes
Can reproduce the issue @Cmd190 described, for 972x720px.

2022-06-23 08:46 UTC, steffenkleinle commented on release-notes/unreleased/IGAPP-1005-double-separation-line-poi-list-bas.yml
> +de: Doppelte Trennlinie in der mobilen Listenansicht der Lokationen entfernt.
Lokationen is definitely not a term we use:
```suggestion
en: Removed double separation line in location list view mobile.
de: Doppelte Trennlinie in der mobilen Listenansicht der Orte entfernt.
```

2022-06-24 14:00 UTC, f1sh1918 commented
> Can reproduce the issue @Cmd190 described, for 972x720px.

well the purpose of this ticket @steffenkleinle as you created was to remove:
"Double separation line in bottom action sheet"

2022-06-24 14:16 UTC, steffenkleinle approved these changes

2022-06-27 09:02 UTC, merged