IGAPP-1027: Save jpal tracking code
digitalfabrik/integreat-app pull request #707
Opened 2022-06-28 15:24 UTC by steffenkleinle

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

- [x] Check whether previously persisted code is deleted on native if clicking on https://integreat.app/jpal (without a tracking code)

2022-06-28 15:26 UTC, steffenkleinle commented on web/src/utils/safeLocalStorage.ts
> +export const PAGE_FORCE_REFRESHED_KEY = 'pageForceRefreshed'
was changed from `page-force-refresh`, should I keep the old one, delete the new one or just change it as it currently is? leads to two values saved in the local storage

2022-06-29 11:46 UTC, f1sh1918 requested changes
Works fine on chrome. Just some minor improvements. We do not need a release note?

2022-06-29 11:46 UTC, f1sh1918 commented on web/src/routes/JpalTrackingPage.tsx
> +const JpalTrackingPage = (): ReactElement => {
```suggestion
const JpalTrackingPage = (): null => {
```

2022-06-29 11:46 UTC, f1sh1918 commented on web/src/routes/JpalTrackingPage.tsx
> +  return <></>
```suggestion
  return null
```

2022-06-29 11:46 UTC, f1sh1918 commented on web/src/routes/JpalTrackingPage.tsx
> +const JpalTrackingPage = (): ReactElement => {
returning null is more performant than returning fragment

2022-06-29 11:46 UTC, f1sh1918 commented on web/src/routes/JpalTrackingPage.tsx
> +import React, { ReactElement, useEffect } from 'react'
```suggestion
import { useEffect } from 'react'
```

2022-06-29 13:28 UTC, steffenkleinle commented
> We do not need a release note?

Because imo this is only a technical task paving the way for another issue. Will write a release note for https://issues.tuerantuer.org/browse/IGAPP-1025 though.

2022-06-29 14:00 UTC, f1sh1918 approved these changes
works fine tested on chrome

2022-07-04 08:02 UTC, SteffiStuffel approved these changes
Tested on chrome

2022-07-04 08:35 UTC, SteffiStuffel approved these changes
Not results shown currently in the logs, therefore not possible to test. Code looks good.

2022-07-04 09:23 UTC, steffenkleinle commented
>     * [x]  Check whether previously persisted code is deleted on native if clicking on https://integreat.app/jpal (without a tracking code)

Currently not working on native, created https://issues.tuerantuer.org/browse/IGAPP-1045

2022-07-04 09:52 UTC, steffenkleinle commented
> Not results shown currently in the logs, therefore not possible to test. Code looks good.

Yes, not yet included in the requests, see #709. Also this is not yet implemented in the backend. However, #709 is testable as described here: https://github.com/digitalfabrik/integreat-app/pull/709#issuecomment-1173580607

2022-07-04 11:00 UTC, merged