IGAPP-835: Remove enzyme on web
digitalfabrik/integreat-app pull request #733
Opened 2022-07-26 09:24 UTC by SteffiStuffel

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Removed tests which only contained snapshot-testing. I can open a ticket with a list of these files, so we write new test for them, if this is wanted. Removed snapshots.

We can also add a custom render-function, which applies the theme automatically, as we have a lot of tests which manually add the ThemeProvider. I can open a ticket for this, too, if wanted.

2022-07-26 12:22 UTC, steffenkleinle requested changes
Finally no more enzyme :tada:

2022-07-26 12:22 UTC, steffenkleinle commented on web/src/components/FeedbackToolbarItem.tsx
> +          title={isPositiveRatingLink ? 'faSmile' : 'faFrown'}
Title should not be used for this purpose, it is shown as a tooltip:
![image](https://user-images.githubusercontent.com/29095487/181003060-98fa4d66-d2c4-4a26-af03-ec9454cfa452.png)
I think you could just remove the tests, they don't really test important stuff.

2022-07-26 12:25 UTC, steffenkleinle commented
> Removed tests which only contained snapshot-testing. I can open a ticket with a list of these files, so we write new test for them, if this is wanted. Removed snapshots.

Wouldn't do this tbh, those issues just live in the backlog for years until they are rejected. When new behavior is added or changed, we should write tests.

> We can also add a custom render-function, which applies the theme automatically, as we have a lot of tests which manually add the ThemeProvider. I can open a ticket for this, too, if wanted.

There are already custom render functions but with `wrapWithTheme` set to false, but you are right, no "basic" render function yet. This could just be changed to fix the problem. However, it is now recommended to use the MemoryRouter if react-router functionality is used. Maybe we should open a ticket to change that.

2022-07-27 07:32 UTC, SteffiStuffel commented on web/src/components/__tests__/NewsTabs.spec.tsx
> +    const { getByLabelText } = renderWithBrowserRouter(
Tried everywhere without and test failed, because of href tags.

2022-08-01 13:49 UTC, f1sh1918 commented
please resolve merge conflicts :)

2022-08-02 06:24 UTC, steffenkleinle approved these changes

2022-08-02 07:46 UTC, SteffiStuffel commented
> please resolve merge conflicts :)

That's not our workflow, because we would have a lot of commits and overhead, if we always keep branches conflict free, while waiting for reviews.

Moreover in this case. these conflicts are just trailing commas stuff.

2022-08-02 08:42 UTC, f1sh1918 approved these changes

2022-08-02 08:49 UTC, merged