IGAPP-1139 Change footer seperation line color to #B1B1B1
digitalfabrik/integreat-app pull request #821
Opened 2022-11-28 12:26 UTC by randowha

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2022-11-28 13:56 UTC, LeandraH approved these changes
Nicely done! Tested on Firefox

2022-11-29 12:38 UTC, steffenkleinle approved these changes
Congrats to your first PR, thank you! :tada: :rocket: Once you applied all prettier changes you are good to merge :)

2022-11-29 12:41 UTC, steffenkleinle commented
@randowha on a minor note: We try to prefix all our commits with the issue number, in your case this would be for example:
`IGAPP-1139: Change footer seperation line color to #B1B1B1`

2023-01-09 13:01 UTC, steffenkleinle requested changes
Looks like your merge somehow failed :/ Also, Why did you revert the usage of our textColor constant back to a magic value?

2023-01-10 10:36 UTC, randowha commented
> 

would

2023-01-10 10:41 UTC, randowha commented
> Looks like your merge somehow failed :/ Also, Why did you revert the usage of our textColor constant back to a magic value?

There is no color #b1b1b1 yet. Would you like me to use the already existing textDecorationColor (#c7c7c7) or to create a new color constant?

2023-01-10 18:53 UTC, LeandraH commented on web/src/components/CityNotCooperatingFooter.tsx.orig
> +>>>>>>> a77968e42d7dc6205176b74dc1798a2bf95c2d01
Looks like a failed merge here. I think the accepted one should be the lower case one, right?

2023-01-10 18:55 UTC, LeandraH commented
> > Looks like your merge somehow failed :/ Also, Why did you revert the usage of our textColor constant back to a magic value?
> 
> There is no color #b1b1b1 yet. Would you like me to use the already existing textDecorationColor (#c7c7c7) or to create a new color constant?

Hmmm, good question, we are now using that color in two places. My usual rule of thumb is to make it a constant after three repeats but we can also make one here already?

2023-01-11 12:44 UTC, randowha commented
Sorry for all these commits, but because of merging main into my branch in the middle of the feature, I find myself unable to squash them together. If sb is able to resolve that, feel free

2023-01-17 10:18 UTC, steffenkleinle approved these changes

2023-01-17 10:18 UTC, steffenkleinle commented on build-configs/common/theme/colors.ts
> +  footerLineColor: 'b1b1b1',
Even so it works fine, I would prefer the hash-prefixed variant for consistency:
```suggestion
  footerLineColor: '#b1b1b1',
```

2023-01-23 12:04 UTC, steffenkleinle approved these changes

2023-01-24 14:46 UTC, merged