IGAPP-1184: Not found error flickering
digitalfabrik/integreat-app pull request #858
Opened 2023-01-25 14:45 UTC by steffenkleinle

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2023-01-27 09:57 UTC, sarahsporck approved these changes
Tested in firefox and on android.

2023-02-01 14:48 UTC, f1sh1918 requested changes
Nice work. couldn't see any flickering issue

Please adjust the wrong imports and re-request review

2023-02-01 14:48 UTC, f1sh1918 commented on web/src/routes/CategoriesPage.tsx
> +import usePreviousProp from 'src/hooks/usePreviousProp'
```suggestion
import usePreviousProp from '../hooks/usePreviousProp'
```

2023-02-01 14:48 UTC, f1sh1918 commented on web/src/routes/EventsPage.tsx
> +import usePreviousProp from 'src/hooks/usePreviousProp'
```suggestion
import usePreviousProp from '../hooks/usePreviousProp'
```

2023-02-06 08:40 UTC, f1sh1918 approved these changes

2023-02-06 10:02 UTC, merged