IGAPP-1179: Poi categories native
digitalfabrik/integreat-app pull request #870
Opened 2023-02-01 13:52 UTC by f1sh1918

Show Poi Category on native app

2023-02-03 13:23 UTC, LeandraH approved these changes
Nice! Tested in emulated Android and real iOS. On selecting one of the POIs, the icon reverts to the general one again by the way, is that the expected behaviour?

2023-02-06 09:51 UTC, SteffiStuffel requested changes
Code looks good, but getting visual bugs, see attached screenshots 
Navigating to Berlin, everything looks fine:
![not yet selected joan miro](https://user-images.githubusercontent.com/18463686/216939938-00ef0834-9f78-4664-94a6-c5fb957fc8b4.png)
Clicking on Joan Miro, berlin icon is just a black circle
![selected joan miro - berlin black](https://user-images.githubusercontent.com/18463686/216939951-43088c93-6a66-419f-9d91-00eea82f0c39.png)
Selecting Berlin, Joan Miro icon is dark
![selected berlin again - joan miro dark](https://user-images.githubusercontent.com/18463686/216939946-5b8ff669-7177-49c4-a981-7edcf9edf8f0.png)

Also i get a lot of ` Mapbox [info] Request failed due to a permanent error: Canceled  {"level": "warning", "message": "Request failed due to a permanent error: Canceled ", "tag": "Mbgl-HttpRequest"}` errors in the console.

2023-02-06 09:51 UTC, SteffiStuffel commented on release-notes/unreleased/IGAPP-1179-poi-categories-native.yaml
> +en: Categories of Location will be shown.
"of **l**ocation**s**"

2023-02-06 15:26 UTC, f1sh1918 commented
> Code looks good, but getting visual bugs, see attached screenshots Navigating to Berlin, everything looks fine: ![not yet selected joan miro](https://user-images.githubusercontent.com/18463686/216939938-00ef0834-9f78-4664-94a6-c5fb957fc8b4.png) Clicking on Joan Miro, berlin icon is just a black circle ![selected joan miro - berlin black](https://user-images.githubusercontent.com/18463686/216939951-43088c93-6a66-419f-9d91-00eea82f0c39.png) Selecting Berlin, Joan Miro icon is dark ![selected berlin again - joan miro dark](https://user-images.githubusercontent.com/18463686/216939946-5b8ff669-7177-49c4-a981-7edcf9edf8f0.png)
> 
> Also i get a lot of ` Mapbox [info] Request failed due to a permanent error: Canceled {"level": "warning", "message": "Request failed due to a permanent error: Canceled ", "tag": "Mbgl-HttpRequest"}` errors in the console.

@SteffiStuffel these look like common emulator bugs on android. could you please test (and maybe confirm) this issue on real device. We receive this warning error in all devices even if it works. Is a maplibre issues (happens f.e. also in entitlementcard)

2023-02-07 10:57 UTC, SteffiStuffel approved these changes

2023-02-07 12:24 UTC, merged