IGAPP-1137: Maps attribution
digitalfabrik/integreat-app pull request #885
Opened 2023-02-21 14:07 UTC by f1sh1918

OpenStreetMaps attribution will now be displayed for web and native

Requirements are fulfilled (https://www.openstreetmap.org/copyright)
- show correct text: © OpenStreetMap contributors (https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- provide link to: https://www.openstreetmap.org/copyright

Note: To show the attribution icon for mobile web, i had to reposition the geocontrol button. I did it same way as on native to reposition if bottom action sheet changes. Additionally i hided the unneeded `NavigationControl` on mobile since you zoom with your fingers

2023-02-21 14:07 UTC, f1sh1918 commented on native/src/components/Link.tsx
> +  style?: StyleProp<TextStyle>
needed to override standard padding

2023-02-22 14:07 UTC, LeandraH approved these changes
Code looks good, only tested in Firefox, my native build is currently not working

2023-02-22 14:11 UTC, sarahsporck requested changes
Copyright not visible in web mobile. (seems to be below BottomActionSheet)
Also link seems to be missing in web desktop.
(Tested on Safari)

Native is fine :)

2023-02-22 14:11 UTC, sarahsporck commented on web/src/components/MapAttribution.tsx
> +  color: rgba(0, 0, 0, 0.75);
Should be the same as in the footer overlay imo.
```suggestion
  background-color: rgba(255, 255, 255, 0.5);
  box-shadow: 0 2px 3px 3px rgba(0, 0, 0, 0.1);
  color: rgba(0, 0, 0, 0.75);
```

2023-02-22 14:31 UTC, f1sh1918 commented
> Copyright not visible in web mobile. (seems to be below BottomActionSheet) Also link seems to be missing in web desktop. (Tested on Safari)
> 
> Native is fine :)

@sarahsporck
What do you mean by link seems to be missing?
Works fine for me on safari desktop

I also tested the geocontrol on safari mobile view and its slow but working. I guess this is due to the emulator and gonna test it on my iPhone

https://user-images.githubusercontent.com/37902063/220652554-cc2e6378-3ae8-4ecb-ba81-1d5896dc2b7e.mov

2023-02-22 14:41 UTC, f1sh1918 commented on native/src/components/MapsAttribution.tsx
> +  font-size: ${props => (props.expanded ? '14px' : '20px')};
these fonts are in rem and can't be used for native `decorativeFontSizeSmall: '0.7rem'`

2023-02-23 09:20 UTC, sarahsporck commented on native/src/components/MapsAttribution.tsx
> +  font-size: ${props => (props.expanded ? '14px' : '20px')};
ah okay. 👍🏼

2023-02-23 09:21 UTC, sarahsporck approved these changes
Tested in Safari again and works fine now. Maybe I was on the wrong branch while testing web. ^^

2023-02-23 12:03 UTC, merged