IGAPP-1256: Remove placeholder icon
digitalfabrik/integreat-app pull request #897
Opened 2023-03-13 10:35 UTC by sarahsporck

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2023-03-13 15:40 UTC, LeandraH approved these changes
Nice! Tested in Firefox and simulated iOS

2023-03-13 15:40 UTC, LeandraH commented on release-notes/unreleased/IGAPP-1256-change-circle-icons.yml
> +de: Entfernen des Platzhalter Symbols in der Kategorienlisten.
```suggestion
de: Entfernen des Platzhalter-Symbols in den Kategorienlisten.
```

2023-03-21 16:54 UTC, f1sh1918 requested changes
I just checked the proposed design
https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Jira?node-id=830-750&t=WKp8IRlXK40Dj8Rj-0
The border should take the whole space. I think it has to be discussed what happens with second lvl categories but currently it looks very weird in my opinion. Please request a complete list design from ui/ux.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/37902063/226684028-97d6dec3-d79b-46c0-a4ef-1eb3e4696155.png">

2023-03-27 07:57 UTC, sarahsporck commented
> I just checked the proposed design
> https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Jira?node-id=830-750&t=WKp8IRlXK40Dj8Rj-0
> The border should take the whole space. I think it has to be discussed what happens with second lvl categories but currently it looks very weird in my opinion. Please request a complete list design from ui/ux.

👍🏼 werde mich nochmal mit toni dazu austauschen und dann nen neuen PR öffnen.

2023-03-27 07:57 UTC, closed without merging