IGAPP-1327: Make translations consistent
digitalfabrik/integreat-app pull request #959
Opened 2023-06-28 11:24 UTC by steffenkleinle

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2023-06-28 11:31 UTC, steffenkleinle commented
This PR
* Removes tunews keys and instead uses common news ones
* Changes German wording from formal to informal (sie -> du) and removes affected translations
* Moves the key "textCopied" to common and renames to "copied"

2023-06-29 14:46 UTC, LeandraH reviewed
Nice! Tested on emulated iOS

2023-06-29 14:46 UTC, LeandraH approved these changes
Arg

2023-07-05 13:09 UTC, sarahsporck requested changes
Tested on android emulator and web

2023-07-05 13:09 UTC, sarahsporck commented on web/src/components/CityContentToolbar.tsx
> +      <Tooltip text={t('common:textCopied')} flow='up' active={linkCopied} trigger='click'>
```suggestion
      <Tooltip text={t('common:copied')} flow='up' active={linkCopied} trigger='click'>
```

2023-07-05 13:27 UTC, steffenkleinle commented on web/src/components/CityContentToolbar.tsx
> +      <Tooltip text={t('common:textCopied')} flow='up' active={linkCopied} trigger='click'>
Good catch, thanks!

2023-07-07 09:46 UTC, sarahsporck approved these changes

2023-07-07 09:46 UTC, merged